### ISSUE TITLE
[native_pdf_view] native_pdf_renderer render image with black BG

### ISSUE THREAD

**Issue by eliaweiss** [rbcprolabs/packages.flutter#101]
![2020-07-18 113848 556528](https://user-images.githubusercontent.com/4609092/87849079-66c24200-c8ee-11ea-9663-10e6b18c428f.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SergeShkurko** [comment]
@eliaweiss can you attach file?

**Comment by SergeShkurko** [comment]
If I attach the document I will open it again
