### ISSUE TITLE
[native_pdf_view] Missing Plugin Exception - io.scer.pdf.renderer

### ISSUE THREAD

**Issue by atnegrete** [rbcprolabs/packages.flutter#104]
**Describe the bug**
Exception is being thrown when calling PdfDocument.openAsset

**To Reproduce**
1. PDFDocument.openAsset('assets/pdf.pdf');

**Smartphone (please complete the following information):**
 - Android Emulator Nexus_10_API_28

**Additional context**
E/flutter ( 4346): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method open.document.asset on channel io.scer.pdf.renderer)
E/flutter ( 4346): #0      MethodChannel._invokeMethod 
E/flutter ( 4346): <asynchronous suspension>
E/flutter ( 4346): #1      MethodChannel.invokeMethod 
E/flutter ( 4346): #2      PDFDocument.openAsset 
E/flutter ( 4346): #3      _UserFormPdfPageState.initState.<anonymous closure> 
E/flutter ( 4346): #4      new Future.microtask.<anonymous closure>  (dart:async/future.dart:202:37)
E/flutter ( 4346): #5      _rootRun  (dart:async/zone.dart:1180:38)
E/flutter ( 4346): #6      _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 4346): #7      _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 4346): #8      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 4346): #9      _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 4346): #10     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 4346): #11     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 4346): #12     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 4346): #13     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 4346): #14     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)

**Comment by SergeShkurko** [comment]
1. Stop build
2. Run `flutter clean`
3. Run `flutter pub get`
4. Run project again

About `Missing Plugin Exception - io.scer.pdf.renderer` - you installed the package while the application was running. Plugins with native code require a full stop and restart to register the native code with a framework
