### ISSUE TITLE
[native_pdf_view] Open PDF file from computer on Web

### ISSUE THREAD

**Issue by sonth-bhsoft** [rbcprolabs/packages.flutter#108]
I try to load a PDF file from my computer on web. After go through all issues, I've found that it can only be done with PdfDocument.openData(Uint8List data).
I've try it already but I got an error **PlatformException(error, TypeError: Cannot read property 'getDocument' of undefined, null)**
Has anyone run into the same problem?

**Comment by sonth-bhsoft** [comment]
FYI, it turns our that I've forgotten to add support lines into index.html

**Comment by Tapasm1212** [comment]
It's not working on the web after adding the script in the index.html

**Comment by dan1229** [comment]
Same issue as above - the <script> tags are in my index.html

**Comment by mprogers** [comment]
I just ran into this problem on iPadOS... has this been resolved?
