### ISSUE TITLE
Zoom factor resets after page switchover while animation

### ISSUE THREAD

**Issue by KarlKl** [rbcprolabs/packages.flutter#114]
**Describe the bug**
When a zoom factor is active and you call `animateToPage` and one page switches over to another, the zoom factor gets resetted.

**To Reproduce**
1. Open multi-page PDF
2. Zoom in to page
3. Call `animateToPage(3)`
4. As soon as the second page appears, the zoom factor gets resetted

**Expected behavior**
Zoom factor should be kept.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Version 3.8.0

**Comment by SergeShkurko** [comment]
Already fixed
