### ISSUE TITLE
Epub View | picture_stream

### ISSUE THREAD

**Issue by akinfurkan13** [rbcprolabs/packages.flutter#116]
Xcode's output:
↳
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^

flutter doctor -v 

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale tr-TR)
    • Flutter version 1.20.2 at /Users/furkan/Developer/flutter
    • Framework revision bbfbf1770c (2 hafta önce), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/furkan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • B67F2FC2-11F2-44B8-9AAA-5BE7D5858CF0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

flutter channel stable

**Comment by SergeShkurko** [comment]
For hot solution try it:
```dart
dependency_overrides:
  # flutter_html usages flutter_svg, DiagnosticableMixin problem
  flutter_svg: ^0.18.0
```

**Comment by akinfurkan13** [comment]
I added but different error came.

Because no versions of epub_view match >1.0.0 <2.0.0 and epub_view 1.0.0 depends on epub ^2.1.0, epub_view ^1.0.0 requires epub ^2.1.0.
And because no versions of epub match >2.1.0 <3.0.0 and epub 2.1.0 depends on xml >=2.6.0 <4.0.0, epub_view ^1.0.0 requires xml >=2.6.0 <4.0.0.
Because flutter_svg >=0.18.1 depends on xml ^4.2.0 and flutter_svg >=0.18.0 <0.18.1 depends on xml ^4.1.0, flutter_svg >=0.18.0 requires xml ^4.1.0.
Thus, epub_view ^1.0.0 is incompatible with flutter_svg >=0.18.0.       
So, because kitap depends on both epub_view ^1.0.0 and flutter_svg ^0.18.0, version solving failed.

**Comment by SergeShkurko** [comment]
use:
```yaml
  epub_view:
    git:
      url: https://github.com/rbcprolabs/packages.flutter.git
      path: packages/epub_view
```

now i can't publish package with dependency from git, awaiting publishing `epub` package with dependency xml >= 4.0.0
