### ISSUE TITLE
Initial page isn't working

### ISSUE THREAD

**Issue by MeitanteiAshour** [rbcprolabs/packages.flutter#119]
I've been working on the PDFController object , I stated an initial page and yet it always opens on the first page.

Expected Behavior : 
Should get me to the initial page.

Screenshots : 
![image](https://user-images.githubusercontent.com/50237142/91882435-3dcdf480-ec83-11ea-93cd-883fa9f3a41d.png)
![image](https://user-images.githubusercontent.com/50237142/91882477-4e7e6a80-ec83-11ea-92d3-ebae367c1d19.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 Emulator
 - Version : API 27 - x86 emulator

Working on the latest version of plugin :   native_pdf_view: ^3.8.0

**Comment by marcqtan** [comment]
same here

**Comment by SachinBhankhar** [comment]
Any solutions?

**Comment by Fethi1** [comment]
same problem for me

**Comment by Fethi1** [comment]
i had to use this workaround to solve it
`  pdfController = PdfController(
      document: PdfDocument.openFile(widget.book.path),
      initialPage: page_number,
    );
    Future.delayed(Duration(milliseconds: 500), () {
      pdfController.animateToPage(int.parse(widget.book.last_page_opened),
          duration: Duration(milliseconds: 500), curve: Curves.ease);
    });`

**Comment by SachinBhankhar** [comment]
> i had to use this workaround to solve it, which is basically animate to the desired page after a certain delay
> ` pdfController = PdfController( document: PdfDocument.openFile(widget.book.path), initialPage: page_number, ); Future.delayed(Duration(milliseconds: 500), () { pdfController.animateToPage(int.parse(widget.book.last_page_opened), duration: Duration(milliseconds: 500), curve: Curves.ease); });`

I used the same trick

**Comment by SergeShkurko** [comment]
`InitialPage` not passed here

https://github.com/rbcprolabs/packages.flutter/blob/e7f6527d8e1f28775063963e451d421d9e1e1221/packages/native_pdf_view/lib/src/native_pdf_controller.dart#L134

**Comment by SergeShkurko** [comment]
published [native_pdf_view] v3.9.1 with fix
