### ISSUE TITLE
Ask for Linux support

### ISSUE THREAD

**Issue by yingshaoxo** [rbcprolabs/packages.flutter#125]
I'm working on a project: https://github.com/yingshaoxo/flutter-ocr

It needs a PDF library.

**Comment by SergeShkurko** [comment]
I do not know C/C++ for add support Windows / linux platforms

**Comment by yingshaoxo** [comment]
> I do not know C/C++ for add support Windows / linux platforms

Alright, thank you for your time.

It's OK.

Now I think maybe write everything with flutter is not a good idea. (Think it as a frontend framework would be better

**Comment by sgehrman** [comment]
been over a year, still waiting

**Comment by RadJKW** [comment]
Also waiting on this. This package https://pub.dev/packages/printing used pdfium and has a PdfPreview widget for flutter
