### ISSUE TITLE
Opening urls is not supported???

### ISSUE THREAD

**Issue by pheromone** [rbcprolabs/packages.flutter#126]
![image](https://user-images.githubusercontent.com/14305431/97650127-f651c200-1a93-11eb-9ee2-c25ea8452d56.png)
Opening urls is not supported???

**Comment by nilsreichardt** [comment]
We miss this feature! Our use case: users can share their pdfs and view in the app. But they can't open any links...

**Comment by nilsreichardt** [comment]
@pheromone Any reasons for closing this Ticket? So I opened a new ticket: #148

**Comment by pheromone** [comment]
Nothing, did I give up the plugin。
