### ISSUE TITLE
Error: Type 'PdfController' not found

### ISSUE THREAD

**Issue by JAICHANGPARK** [rbcprolabs/packages.flutter#129]
**Describe the bug**

I tried to import `import 'package:native_pdf_view/native_pdf_view.dart';`
But Now I had some problem about this issuses 

```
Error: 'PdfController' isn't a type.
```

**Comment by JAICHANGPARK** [comment]
I changed to from `device_info: ^0.4.2+10` to `device_info: ^1.0.0`

**Comment by SergeShkurko** [comment]
published package native_pdf_view v 3.9.0 with some fixes and upgraded device_info
