### ISSUE TITLE
[epub_view] Unable to build on iOS

### ISSUE THREAD

**Issue by GONZALEZD** [rbcprolabs/packages.flutter#130]
I started a new flutter project, then added epub_view package, and finally copy-paste complete example we can find in pub.package website (https://pub.dev/packages/epub_view/example).

I tests these library imports:
- epub_view: 1.0.0
- epub_view: any

I also added my epub asset correctly (i mean in the application and in yaml file).

Everytime I try to compile the application for iOS, I get this errors:
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);

**Comment by GONZALEZD** [comment]
BUT when I tried to link to my project the epub_view to the local repository, then it works O_O.
I mean that I downloaded the git repository (https://github.com/rbcprolabs/packages.flutter.git ), then in my yaml file, I linked to the local version:

# pubspec.yaml file
  epub_view:
    path: ../../tests/packages.flutter/packages/epub_view

That's a workaround, but not comfortable at all, as pud.package should be reliable... :/

**Comment by SergeShkurko** [comment]
i can't publish update epub_view 1.1 to pub (problem with old 'epub' package on pub)
temporary you can use version epub_view from repository

**Comment by SergeShkurko** [comment]
https://dart.dev/tools/pub/dependencies#git-packages
