### ISSUE TITLE
native_pdf_view - extended_image error

### ISSUE THREAD

**Issue by zs-dima** [rbcprolabs/packages.flutter#133]
reference 'native_pdf_view: ^3.8.0'

> flutter channel dev
> flutter upgrade

- it will lead to the error:
/extended_image-1.3.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.

**Comment by zs-dima** [comment]
temporary solution could be

```
dependency_overrides:
  extended_image: ^1.3.1-dev
```

but it is not really good solution

**Comment by BartusZak** [comment]
Thanks, that works!

I'm sharing my env configuration and error messages for others.

**Flutter version:**
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (13 days ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)

flutter run -d chrome
Running "flutter pub get" in ...                  1 314ms
Launching lib\main.dart on Chrome in debug mode...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-1.3.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^

**Added:**
dependency_overrides:
  extended_image: ^1.3.1-dev

**Result:**
flutter run -d chrome
Warning: You are using these overridden dependencies:                   
! extended_image 1.3.1-dev
Running "flutter pub get" in multibook-frame...                  1 168ms
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                  32,5s
Debug service listening on ws://127.0.0.1:55590/SvD2-wZNR4Y=/ws

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

**Comment by givip** [comment]
> temporary solution could be
> 
> ```
> dependency_overrides:
>   extended_image: ^1.3.1-dev
> ```
> 
> but it is not really good solution

Better solution, still temporary 
```
dependency_overrides:
  extended_image: 1.5.0-dev
```

**Comment by SergeShkurko** [comment]
published [native_pdf_view] v3.9.1 with extended_image v1.5.0

**Comment by BrayFlex** [comment]
> published [native_pdf_view] v3.9.1 with extended_image v1.5.0

![image](https://user-images.githubusercontent.com/33260515/109516245-f8458500-7a75-11eb-9c82-fc545fe2a6f2.png)

**Comment by SergeShkurko** [comment]
@BrayFlex now support only flutter stable channel

**Comment by christophemacabiau** [comment]
I have this problem with flutter Channel stable, 2.0.6, native_pdf_view: ^3.9.0
and
dependency_overrides:
  extended_image: ^1.5.0

what is the correct combination?

Thanks for your help :-)

**Comment by christophemacabiau** [comment]
seems to work with
dependency_overrides:
  extended_image: 1.5.0-dev
