### ISSUE TITLE
native_pdf_renderer support HTML to PDF

### ISSUE THREAD

**Issue by Sun3** [rbcprolabs/packages.flutter#136]
**Is your feature request related to a problem? Please describe.**
Currently there's no support to create PDF Files from HTML that work with Flutter Web.

**Describe the solution you'd like**
Create PDF File from HTML that works with Flutter Web.

**Describe alternatives you've considered**
I have looked at other alternatives but I have not found any packages that handle it for the Web.

Thank you.

**Comment by SergeShkurko** [comment]
@Sun3 generating pdf, web also supports https://pub.dev/packages/pdf
demo: https://davbfr.github.io/dart_pdf/#/

**Comment by Sun3** [comment]
@SergeShkurko I tried the pdf package (I like it), unfortunately they do not create PDF from HTML for the web (mobile HTML to PDF is only via print) and are not planning to support it in the future.

Thanks.
