### ISSUE TITLE
Plugin error should be catchable

### ISSUE THREAD

**Issue by Tahaan** [rbcprolabs/packages.flutter#14]
**Package name**
A name of package whom this bug concerns. Ex. `native_pdf_renderer`

**Describe the bug**
On error in the package the entire app crashes and closes.

**To Reproduce**
1. ListView.builder
2. Returns a Card with a FutureBuilder in the ListView which returns an "Image" as a thumbnail of a FILE BASED PDF file (downloaded from the internet to INTERNAL STORAGE)
3. Scroll rapidly down a long list
4. The problem is intermittend but happens often

**Expected behavior**
Throw a catchable exception

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Android Emulator API 28
 - OS: Android 9
 - Version [28]

**Additional context**
Below 3 items that worked OK before the next one caused the error.

D/PDF_RENDER( 3424): OpenFileDocument. File: /data/user/0/za.co.mydomain.myapp/app_flutter/Cache/d503a6e1-4be2-4f33-9504-eb4072c26afb.pdf
D/PDF_RENDER( 3424): OpenFileDocument. File: /data/user/0/za.co.mydomain.myapp/app_flutter/Cache/36d1d5da-2086-4d29-a283-4dbb1615bcbd.pdf
D/PDF_RENDER( 3424): OpenFileDocument. File: /data/user/0/za.co.mydomain.myapp/app_flutter/Cache/b6371a15-b068-497c-a410-98cf9ad9a321.pdf
E/AndroidRuntime( 3424): FATAL EXCEPTION: Thread-7
E/AndroidRuntime( 3424): Process: za.co.mydomain.myapp, PID: 3424
E/AndroidRuntime( 3424): io.scer.pdf.renderer.resources.RepositoryItemNotFoundException: 7c4172e9-dcb7-44b7-99f5-0e5f32822ff7
E/AndroidRuntime( 3424): 	at io.scer.pdf.renderer.resources.Repository.get(Repository.kt:12)
E/AndroidRuntime( 3424): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)
E/AndroidRuntime( 3424): 	at java.lang.Thread.run(Thread.java:764)
I/Process ( 3424): Sending signal. PID: 3424 SIG: 9

**Comment by SergeShkurko** [comment]
I have an idea what could be the problem. The plugin is not yet able to simultaneously process a large number of pages. As a workaround, you can use: https://pub.dev/packages/synchronized

**Comment by RenanDelfanti** [comment]
@SergeShkurko Do you have an example how to use synchronized to prevent this issue?

**Comment by RenanDelfanti** [comment]
solved the problem by placing a one second splash screen on a stack widget

**Comment by SergeShkurko** [comment]
@RenanDelfanti you cant try use native_pdf_renderer 1.7.0-dev.1

**Comment by RenanDelfanti** [comment]
@SergeShkurko I have same error.

> E/AndroidRuntime(16771): FATAL EXCEPTION: Thread-15
E/AndroidRuntime(16771): Process: br.com.bmtcloud.jasaudeanimal, PID: 16771
E/AndroidRuntime(16771): java.lang.IllegalStateException: Current page not closed
E/AndroidRuntime(16771): 	at android.graphics.pdf.PdfRenderer.throwIfPageOpened(PdfRenderer.java:269)
E/AndroidRuntime(16771): 	at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:224)
E/AndroidRuntime(16771): 	at io.scer.pdf.renderer.document.Document.openPage(Document.kt:30)
E/AndroidRuntime(16771): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)
E/AndroidRuntime(16771): 	at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation(16771): eglMakeCurrent: 0xe673f1c0: ver 3 1 (tinfo 0xd7ecf2a0)

**Comment by RenanDelfanti** [comment]
My pubspec:

```
native_pdf_view: ^2.1.1
native_pdf_renderer: ^1.7.0
```

**Comment by SergeShkurko** [comment]
@Tahaan , @RenanDelfanti 
```yaml
native_pdf_view: ^2.2.0
native_pdf_renderer: ^1.8.1
```
