### ISSUE TITLE
Sound null safety

### ISSUE THREAD

**Issue by graknol** [rbcprolabs/packages.flutter#147]
Title says it all; this package should release a nullsafety pre-release version.

Guide: https://dart.dev/null-safety/migration-guide

EDIT: Most of the work has already been done by @nyarian: [here](https://github.com/Three-Horsemen-of-Software-Engineering/packages.flutter/tree/native_pdf_renderer/migration/null-safety)
Now we just need to wait for https://github.com/Daegalus/dart-uuid/issues/50 to get merged.

TODO:
- [x] Migrate the code - [fork](https://github.com/Three-Horsemen-of-Software-Engineering/packages.flutter/tree/native_pdf_renderer/migration/null-safety)
- [x] Dependency: extension - https://github.com/rbcprolabs/packages.dart/pull/8
- [x] Dependency: uuid - https://github.com/Daegalus/dart-uuid/issues/50

**Comment by tsinis** [comment]
Hey @graknol  and @SergeShkurko 

Thanks for packages! Just letting you know that [uuid](https://github.com/Daegalus/dart-uuid/issues/50) migration is done. Any chance to have pre-release version of all packages with null-safety enabled? Thanks.

**Comment by nyarian** [comment]
@tsinis 
I don't think so, honestly, at least not as fast. Some Flutter plugins here have a set of external dependencies not yet migrated to null-safety, sadly. But you could try your luck searching through the forks - some of them might have necessary null-safety migrations you seek.

**Comment by SergeShkurko** [comment]
extension published [0.2.0-nullsafety.0](https://pub.dev/packages/extension/versions/0.2.0-nullsafety.0)

**Comment by SergeShkurko** [comment]
published v3 with null-safety & flutter v2 capability
https://pub.dev/packages/native_pdf_renderer

about native_pdf_view: https://github.com/rbcprolabs/packages.flutter/issues/166#issuecomment-791260761

**Comment by SergeShkurko** [comment]
native_pdf_view
_Attention **DEV**!_

temporary resolution for null safety & flutter v2:
```yaml
  native_pdf_view:
    git:
      url: https://github.com/rbcprolabs/packages.flutter.git
      ref: feature/nnbd-pdf_view
      path: packages/native_pdf_view
```

**Comment by SergeShkurko** [comment]
published auto_animated & flutter_color with null safety & flutter v2

**Comment by nipunasudha** [comment]
Package doesn't seem to still have null safety. Could you please update us about the progress, and a timeline? :)

![image](https://user-images.githubusercontent.com/17500323/110392180-8b8e4400-808e-11eb-8a13-b4e99dbe4fdc.png)

**Comment by SergeShkurko** [comment]
published null-safety

native_pdf_view v4
epub_view v2
