### ISSUE TITLE
[native_pdf_view] Pdfview can't load when use inside Pageview.

### ISSUE THREAD

**Issue by AverageChau** [rbcprolabs/packages.flutter#155]
PageView(
            children: [
              PdfView(
                documentLoader: Text('Loading'),
                controller: pdfController,
                scrollDirection: Axis.vertical,
              ),
              Center(
                child: Text(
                  'page 2',
                ),
              )
            ],
          ),

It works on the first load, then if you go to page 2 and go back (sometime you need to do it 2-3 times), the pdfview will stuck at loading widget.

First it show as expect.
<img width="198" alt="Screenshot 2021-02-01 235517" src="https://user-images.githubusercontent.com/25887242/106491066-0fca3600-64e9-11eb-97c7-e4fce80d98a6.png">

go to page 2.
<img width="192" alt="Screenshot 2021-02-01 235532" src="https://user-images.githubusercontent.com/25887242/106491161-27a1ba00-64e9-11eb-99f6-fcf7283788b5.png">

back to page 1, it stucks at this
<img width="193" alt="Screenshot 2021-02-01 235542" src="https://user-images.githubusercontent.com/25887242/106491219-36886c80-64e9-11eb-94e9-ad24deef0f53.png">

**Comment by burakcbdn** [comment]
I fixed this issue by using AutomaticKeepAliveClientMixin

in this way when pdf is rendered it will stay alive, and will not need to be rerendered.

here is the code:

```dart
Container(
              child: PageView(
                scrollDirection: Axis.vertical,
                children: pdfControllers
                    .map((controller) => CatalogPDF(
                          controller: controller,
                        ))
                    .toList(),
              ),
            )
```

CatalogPDF:

```dart
class CatalogPDF extends StatefulWidget {
  final PdfController controller;

  const CatalogPDF({Key key, this.controller}) : super(key: key);

  @override
  _CatalogPDFState createState() => _CatalogPDFState();
}

class _CatalogPDFState extends State<CatalogPDF>
    with AutomaticKeepAliveClientMixin {

  int page;
  int maxPage;

  @override
  void initState() {

    super.initState();

    page = widget.controller.initialPage;


  }

  @override
  Widget build(BuildContext context) {
    return Container(
        key: Key(widget.controller.hashCode.toString()),
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        child: Stack(
          children: [
            PdfView(
              controller: widget.controller,
              scrollDirection: Axis.vertical,
              onPageChanged: (newPage) {
                setState(() {
                  page = newPage;
                });
              },
            ),
            Positioned(
                top: 20,
                right: 20,
                child: Material(
                  elevation: 4,
                  borderRadius: BorderRadius.circular(5),
                  child: Container(
                      height: 25,
                      width: 50,
                      child: Center(
                          child: Text(
                    "$page/0",
                    style: TextStyle(fontSize: 15, fontWeight: FontWeight.w500),
                  ))),
                ))
          ],
        ));
  }

  @override
  bool get wantKeepAlive => true;
}
```
