### ISSUE TITLE
initialPage Not working

### ISSUE THREAD

**Issue by MisterB2B** [rbcprolabs/packages.flutter#157]
NATIVE_PDF_VIEW

I've set initialPage to 3, and once the PDF is loaded, it show me the first page...

_pdfController = PdfController(
      initialPage: 3,
      document: PdfDocument.openFile(widget.link),
    );

**Comment by vsutedjo** [comment]
I have the same issue, tested on Android phones.

**Comment by rakib205** [comment]
same issue.

**Comment by SergeShkurko** [comment]
Duplicate of #119
