### ISSUE TITLE
crash app

### ISSUE THREAD

**Issue by AnhTu6610** [rbcprolabs/packages.flutter#16]
E/AndroidRuntime(22186): FATAL EXCEPTION: Thread-123
E/AndroidRuntime(22186): Process: com.abcd.bookse, PID: 22186
E/AndroidRuntime(22186): java.lang.IllegalStateException: Current page not closed
E/AndroidRuntime(22186): 	at android.graphics.pdf.PdfRenderer.throwIfPageOpened(PdfRenderer.java:273)
E/AndroidRuntime(22186): 	at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:226)
E/AndroidRuntime(22186): 	at io.scer.pdf.renderer.document.Document.openPage(Document.kt:30)
E/AndroidRuntime(22186): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)
E/AndroidRuntime(22186): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(22186): FATAL EXCEPTION: Thread-125
E/AndroidRuntime(22186): Process: com.anhtudev.bookse, PID: 22186
E/AndroidRuntime(22186): java.lang.IllegalStateException: Current page not closed
E/AndroidRuntime(22186): 	at android.graphics.pdf.PdfRenderer.throwIfPageOpened(PdfRenderer.java:273)
E/AndroidRuntime(22186): 	at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:226)
E/AndroidRuntime(22186): 	at io.scer.pdf.renderer.document.Document.openPage(Document.kt:30)
E/AndroidRuntime(22186): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)
E/AndroidRuntime(22186): 	at java.lang.Thread.run(Thread.java:764)
I/Process (22186): Sending signal. PID: 22186 SIG: 9
Lost connection to device.

**Comment by SergeShkurko** [comment]
@AnhTu6610 can you attach the code that caused the error?

**Comment by SergeShkurko** [comment]
@AnhTu6610 any news?

**Comment by deepss1** [comment]
Facing the same issue in Android (yet to check in iOS)

Scenario explanation : 

App closes on trying to open the PDF.
I have two functionality in the app which uses this plugin.
1. View PDF 
2. Share a PDF page as image.

2nd works just fine. But when trying to view PDF it force closes the app.

**Comment by SergeShkurko** [comment]
Do you close the page before opening a new one?

**Comment by SergeShkurko** [comment]
For example: https://github.com/rbcprolabs/packages.flutter/blob/master/packages/native_pdf_renderer/example/lib/main.dart#L129

**Comment by SergeShkurko** [comment]
try it: https://github.com/rbcprolabs/packages.flutter/issues/29#issuecomment-591355512

**Comment by SergeShkurko** [comment]
@AnhTu6610 , @deepss1 
```yaml
native_pdf_view: ^2.2.0
native_pdf_renderer: ^1.8.1
```
