### ISSUE TITLE
[epub_view] DiagnosticableMixin class not found due to flutter_svg outdated

### ISSUE THREAD

**Issue by manuelvargastapia** [rbcprolabs/packages.flutter#160]
**Describe the bug**
Error "DiagnosticableMixin class not found" when _running_ the project --not at compile time.

**To Reproduce**
1. Create a new flutter project
2. Install epub_view: ^1.0.0
3. Replicate example code
4. Run project

**Expected behavior**
Compile and run without errors

**Additional context**
The error seems to be related to an updated flutter_svg version [according to this issue](https://github.com/dnfield/flutter_svg/issues/368).

**Suggested workaround**
On my first try, I simply override the flutter_svg dependency. But this produces a new error where epub library becomes incompatible with flutter_svg because each one depends on different versions of xml library. Thus, I followed [this suggestion](https://github.com/orthros/dart-epub/issues/82) to solve the problem and now the project runs fine.

**Comment by SergeShkurko** [comment]
See https://github.com/rbcprolabs/packages.flutter/issues/130#issuecomment-747482205

**Comment by manuelvargastapia** [comment]
Thanks, @SergeShkurko !
