### ISSUE TITLE
Because native_pdf_renderer 2.4.0 depends on device_info ^1.0.0  

### ISSUE THREAD

**Issue by sgehrman** [rbcprolabs/packages.flutter#164]
Because native_pdf_renderer 2.4.0 depends on device_info ^1.0.0 and no versions of native_pdf_renderer match >2.4.0 <3.0.0, native_pdf_renderer ^2.4.0 requires device_info ^1.0.0.

**Comment by SergeShkurko** [comment]
published v3 with null-safety & flutter v2 capability
https://pub.dev/packages/native_pdf_renderer
