### ISSUE TITLE
[native_pdf_view] Issue when updating to Flutter 2.0 (extended_image)

### ISSUE THREAD

**Issue by fvisticot** [rbcprolabs/packages.flutter#166]
**Describe the bug**
I get the error during compilation:

`../.pub-cache/hosted/pub.dartlang.org/extended_image-1.6.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
../development/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {`

**To Reproduce**
using native_pdf_view: ^3.9.1

**Expected behavior**
compilation OK

**Comment by epynic** [comment]
That should be posted here https://github.com/fluttercandies/extended_image/issues

**Comment by SergeShkurko** [comment]
i will change extended_image to https://pub.dev/packages/photo_view today-tomorrow https://github.com/rbcprolabs/packages.flutter/issues/166

**Comment by SergeShkurko** [comment]
i plan to switch to https://pub.dev/packages/photo_view

**Comment by lazylazyllama** [comment]
> i plan to switch to https://pub.dev/packages/photo_view

I would really recommend switching to interactive_viewer it's a build in widget of flutter, in using it myself and it's much better than Photoview, because it has no issues like zoom snapping etc. Which makes it a much more user-friendly experience. Cheers

**Comment by SergeShkurko** [comment]
> I would really recommend switching to interactive_viewer instead of photo_view 

about interactive_viewer - is simple pure zoom control widget, but pdf view need full controlled gallery view (with page switching, zoomed page switching, animation etc)

I don't have much time to do it myself, especially since there are ready-made solutions :)

**Comment by SergeShkurko** [comment]
**pdf_view null-safety & flutter v2**: https://github.com/rbcprolabs/packages.flutter/issues/147#issuecomment-791355014
