### ISSUE TITLE
Native_pdf_view is not null_safety compatible with native_pdf_renderer

### ISSUE THREAD

**Issue by thaodersar** [rbcprolabs/packages.flutter#170]
I am using the latest native_pdf_view 4.0.0 and got this cast error when loading pdf

Unhandled Exception: type 'Future<PdfPageImage?>' is not a subtype of type 'Future<PdfPageImage>' in type cast
[        ] E/flutter (18877): #0      PdfView._render (package:native_pdf_view/src/native_pdf_view.dart:95:9)
[        ] E/flutter (18877): #1      _PdfViewState._getPageImage.<anonymous closure> (package:native_pdf_view/src/native_pdf_view.dart:148:52)
[        ] E/flutter (18877): <asynchronous suspension>
[        ] E/flutter (18877): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)

It cause by these methods:
- native_pdf_view (4.0.0):  static Future<**PdfPageImage**> _render(PdfPage page) 
- native_pdf_renderer (3.0.0): Future<**PdfPageImage?**> render(...)

**Comment by SergeShkurko** [comment]
@thaodersar thanks for remark!

**Comment by SergeShkurko** [comment]
native_pdf_view v4.0.1 published

**Comment by thaodersar** [comment]
thanks for quick fix and release
