### ISSUE TITLE
'native_pdf_renderer/native_pdf_renderer-Swift.h' file not found     #import <native_pdf_renderer/native_pdf_renderer-Swift.h>

### ISSUE THREAD

**Issue by saqibcare** [rbcprolabs/packages.flutter#18]
**In first case with the fresh project of Flutter**
If i am running from command line then the app is running fine on simulator as well on real device. but i am building and running from Xcode then it is giving me following errors.

**Second case is to run with existing application with alot of other plugins**
Then the following error is occurring in both cases, either from terminal or from Xcode.

```
Failed to build iOS app
Error output from Xcode build:
↳
    2019-12-05 11:06:42.202 xcodebuild[22067:169419]  DTDeviceKit: deviceType from 98762ebee0668151686dd01da2abb6186fc9a98a was NULL
    2019-12-05 11:06:42.295 xcodebuild[22067:169419]  DTDeviceKit: deviceType from 98762ebee0668151686dd01da2abb6186fc9a98a was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    **flutter_downloader-cravousdkmjzvhbseqbfmbuiktbf
    /Users/ars/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-1.6.1/ios/Classes/NativePDFRendererPlugin.m:2:9: fatal error: 'native_pdf_renderer/native_pdf_renderer-Swift.h' file not found
    #import <native_pdf_renderer/native_pdf_renderer-Swift.h>**
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    flutter_downloader-cravousdkmjzvhbseqbfmbuiktbf
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'Reachability' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')

```

**Flutter Doctor**
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

• No issues found!
ARSs-Mac-mini:portfolio ars$ 
```
**Following plugins, that i am using**

```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: "8.5.0"
  # flutter_full_pdf_viewer: 1.0.5
  flutter_pdfview: 1.0.0+10
  path: 1.6.4
  path_provider: 0.5.0+1
  chewie: 0.9.8
  http: 0.12.0+2
  json_annotation: ^3.0.0
#  simple_permissions:
  flutter_downloader: 1.2.2
  permission_handler: 3.2.2
  bloc: ^0.15.0
  equatable: 0.5.1
  flutter_bloc: 0.21.0
  sqflite: "1.1.6+4"
  connectivity: 0.4.4
  url_launcher: 5.1.4
  flutter_svg: 0.14.2
  csv: 4.0.3
  spreadsheet_decoder: 1.0.1
  pinch_zoom_image: 0.2.5
  shared_preferences: ^0.4.3
  native_pdf_renderer: ^1.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  video_player:
  json_serializable: ^3.2.0
 
```

Please note: other pdf plugins are commented to use this.

**Comment by SergeShkurko** [comment]
@saqibcare 
1. Package [native_pdf_view] it should be installed as `dependency`, but not `dev_dependency`
2. What version of the package?
3. Do you have compilation swift 5 configured? (#3)

**Comment by saqibcare** [comment]
Here up, mistakenly i have posted the wrong pubspec, in real pubspec file native_pdf_view is under dependency. I have also edit the above comment

```
Because extended_image >=0.6.4 <0.6.8 depends on extended_image_library ^0.1.8 and native_pdf_view >=2.0.0-dev.1 depends on extended_image ^0.6.5, native_pdf_view >=2.0.0-dev.1 requires extended_image_library ^0.1.8 or extended_image ^0.6.8.
And because extended_image >=0.6.8 depends on extended_image_library ^0.1.9 which depends on path_provider ^1.1.2, native_pdf_view >=2.0.0-dev.1 requires path_provider ^1.1.2.
```

Actually i am receiving the given dependency issues because of **native_pdf_view 2.1.0** , therefore i put the **any** here to get the respective compatible version and i got the following version.

```
native_pdf_view:
    dependency: "direct main"
    description:
      name: native_pdf_view
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
```
**So the question is how to resolve the dependency issue first so that i can move forward. May be that error is coming up because of the old version of the plugin.**

**Comment by SergeShkurko** [comment]
@saqibcare any news?

**Comment by tomkuschka** [comment]
Hey, 
we have the same issue in our project. We are using Flutter add-to-existing-app.

@SergeShkurko regarding your comment:
1. yes we have native_pdf_renderer installed as a `dependency`
More specifically we have native_pdf_view (v2.1.1) as a dependency and native_pdf_renderer gets installed automatically 
2. We have the current version of native_pdf_renderer (v1.6.2)
3. We have configured `SWIFT LANGUAGE VERSION` to Swift 5 inside of the Build Settings of our own iOS Project

Does anybody have a clue whats wrong there?

**Comment by SergeShkurko** [comment]
@tomkuschka have tried run `pod install` & `pod update` in ios dir?

**Comment by tomkuschka** [comment]
@SergeShkurko Yes we have tried. On `pod install` it seems like the wrong versions get installed
`Analyzing dependencies
Downloading dependencies
Installing FlutterPluginRegistrant 0.0.1
Installing native_pdf_renderer (1.0.0)
Generating Pods project
Integrating client project
Adding Acknowledgements
Pod installation complete! There are 67 dependencies from the Podfile and 92 total pods installed.`
And on `pod update` nothing happens…

**Comment by SergeShkurko** [comment]
@tomkuschka I had an idea what could be the problem.

last lines from your xcode build error:
```
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'Reachability' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')
```

it seems that xcode cannot normally determine the minimum version of ios to build
you can set it in `/ios/Podfile`
`platform :ios, '8.0'`

![image](https://user-images.githubusercontent.com/18213789/75971812-5bdcb700-5ee3-11ea-99b3-b777808b3711.png)

**Comment by arkadask** [comment]
On file NativePDFRendererPlugin.m can you replace the line 
#import <native_pdf_renderer/native_pdf_renderer-Swift.h>
with the following
#if __has_include(<native_pdf_renderer/native_pdf_renderer-Swift.h>)
#import <native_pdf_renderer/native_pdf_renderer-Swift.h>
#else
// Support project import fallback if the generated compatibility header
// is not copied when this plugin is created as a library.
// https://forums.swift.org/t/swift-static-libraries-dont-copy-generated-objective-c-header/19816
#import "native_pdf_renderer-Swift.h"
#endif

**Comment by matitalatina** [comment]
I just fixed putting `use_frameworks!` in Podfile.

**Comment by jazzbpn** [comment]
> I just fixed putting `use_frameworks!` in Podfile.

Do not work for me. Is there anything I missed? Help me please !!

<img width="706" alt="Screen Shot 2020-05-21 at 20 11 07" src="https://user-images.githubusercontent.com/11361035/82568929-42244500-9b9f-11ea-8461-d3edcfc5e3a6.png">


<img width="908" alt="Screen Shot 2020-05-21 at 20 11 59" src="https://user-images.githubusercontent.com/11361035/82569009-5b2cf600-9b9f-11ea-966b-cada9231014f.png">

**Comment by SergeShkurko** [comment]
@jazzbpn  try run `pod update` in ios dir

**Comment by mnc12004** [comment]
I understand this is an old thread, However, I had the very same issue, but when I added use_frameworks! and uncommented  the line above, the app built out ok.

Needless to say, I had spent a few hours tracking the issue and even deleted the ios folder, which now seems to be an extreme step.

Thanks to this thread though, the problem is resolved and I can move onto the next one (when it arrives).

**Comment by SergeShkurko** [comment]
i find resolve for issue: https://github.com/rbcprolabs/packages.flutter/commit/4bf3a1aa4f54d836bf1d932f11d7c604ea8038a5#diff-e0ed43e59738eb60fb8bb95deb1c3ecaed9f72dd87f2fa4c61cba76334761119R2

publisher in native_pdf_renderer v2.4.0 & native_pdf_view v3.9.0
