### ISSUE TITLE
pageSnapping: false dose not produce the expected behavior.

### ISSUE THREAD

**Issue by kenthinson** [rbcprolabs/packages.flutter#183]
**Describe the bug**
pageSnapping: false should allow someone to scroll to the middle of two pages and stop correct?
If so it's not working in vertical mode on MacOS, and Chrome Web.

**To Reproduce**
1. Create a PdfView.
2. scrollDirection: Axis.vertical,
3. pageSnapping: false,

**Expected behavior**
The page should not snap to the pdf page. It should stop scrolling and wait.

**Screenshots**
![Apr-19-2021 15-41-58](https://user-images.githubusercontent.com/2245494/115300658-d5565980-a125-11eb-8b9f-b763cd9b161a.gif)

**Smartphone (please complete the following information):**
MacOS Desktop, Google Chrome Web.

**Comment by rakib205** [comment]
Facing the same issue.

**Comment by SergeShkurko** [comment]
See https://github.com/rbcprolabs/packages.flutter/issues/6#issuecomment-961061302

**Comment by rakib205** [comment]
Still not working!
