### ISSUE TITLE
Unable to scroll viewport of zoomed page

### ISSUE THREAD

**Issue by kenthinson** [rbcprolabs/packages.flutter#184]
**Describe the bug**
Unable to scroll the image "Page" after enlarged.

**To Reproduce**
Load a pdf. 
Double tap to zoom in.
Scroll down. or right depending on config
The page is "cropped" so you cannot scroll around the enlarged page while zoomed in.

**Expected behavior**
Be able to read the whole document while zoomed in, instead it jumps to the next page.

**Smartphone (please complete the following information):**
Testing Mac Desktop, Chrome Web.

**Comment by SergeShkurko** [comment]
Already fixed
