### ISSUE TITLE
Debug banner always remains active

### ISSUE THREAD

**Issue by jolucas245** [rbcprolabs/packages.flutter#186]
**Describe the bug**
When in debug mode in Flutter, a red stripe is shown: "DebugBanner". This red stripe can be removed using the debugShowCheckedModeBanner: false argument in MaterialApp.
However, when implementing the native_pdf_view dependency, this red stripe appears where the Widget is called. This is an intermediate bug, because when we deploy it, this red band disappears. But it would help a lot in development. If you can fix this, we will be grateful.

**To Reproduce**
1. Create a new Flutter project, and run. You will see that the red debug band is activated.
2. Inside the `MaterialApp()`, put `debugShowCheckedModeBanner: false`, and give a hot restart, you will see that the red band has disappeared.
3. On the MaterialApp `home:`, place the `SfPdfViewer.asset` widget. When it loads, you’ll see that the red stripe has returned
4. It's the bug

**Comment by SergeShkurko** [comment]
@jolucas245 can you attach screenshot?

**Comment by SergeShkurko** [comment]
about `SfPdfViewer.asset`, maybe it another package. native_pdf_view exports `PdfView` widget
