### ISSUE TITLE
[native_pdf_view] Provide a onPageChanged callback

### ISSUE THREAD

**Issue by IchordeDionysos** [rbcprolabs/packages.flutter#19]
**Is your feature request related to a problem? Please describe.**
We would like to show the user that he is on page 1/n, 

**Describe the solution you'd like**
To achieve that I believe that a simple `onPageChanged` callback could be easily implemented and would give us a lot of flexibility.

**Describe alternatives you've considered**
A built-in page indicator would also work, but might not fit into the UI of every app.

**Additional context**

**Comment by SergeShkurko** [comment]
[Code on pastebin](https://pastebin.com/frpKbYLb)

<img width="312" alt="Снимок экрана 2019-12-13 в 16 54 14" src="https://user-images.githubusercontent.com/18213789/70805120-461a9280-1dc9-11ea-90ae-1773f48de789.png">
<img width="304" alt="Снимок экрана 2019-12-13 в 16 54 36" src="https://user-images.githubusercontent.com/18213789/70805121-461a9280-1dc9-11ea-8790-d91bf170f333.png">

@IchordeDionysos  will this solve your problem?

**Comment by SergeShkurko** [comment]
Got your idea, I agree
Added in 2.1.0

**Comment by IchordeDionysos** [comment]
Yes, the example you provided worked, but is so think far less beautiful and less intuitive/obvious to us :)
