### ISSUE TITLE
native_pdf_renderer:: convert pdf into image issue.

### ISSUE THREAD

**Issue by CellCS** [rbcprolabs/packages.flutter#194]
**Describe the bug**
Image is not the view of pdf file.

One page sample pdf. 
[PDF Bookmark Sample.pdf](https://github.com/rbcprolabs/packages.flutter/files/6658591/PDF.Bookmark.Sample.pdf)

**To Reproduce**
Testing on iOS ipadOS 14
```
    final document = await PdfDocument.openFile(filePath);
    final page = await document.getPage(1);
    final pageImage = await page.render(width: page.width, height: page.height);
    await page.close();
    ....
```

Results; 
<img src="https://user-images.githubusercontent.com/16886624/122121003-1d79bb80-cdf9-11eb-9850-7265c6db6f71.png" width="400" alt="imageResult">

**Expected behavior**

**Screenshots**

original Pdf View
<img src="https://user-images.githubusercontent.com/16886624/122121214-5f0a6680-cdf9-11eb-96c3-e156702df292.png" width="400" alt="originalpdf">

**Smartphone (please complete the following information):**
 - Device:ipad
 - OS: ipadOS 14
 - Version : 14

**Additional context**

**Comment by SergeShkurko** [comment]
@CellCS you can set backgroundColor
![image](https://user-images.githubusercontent.com/18213789/122659081-41d4ef80-d18d-11eb-9385-1a9db2cb6baf.jpeg)
