### ISSUE TITLE
PageSnapping false is not working!

### ISSUE THREAD

**Issue by rakib205** [rbcprolabs/packages.flutter#195]
PageSnapping is forcibly set as true in the latest version. It doesn't change scrolling behavior when the value is false.

**Comment by rakib205** [comment]
Is there any fix? My app update is stuck for this.
Looking forward to hearing from you.
Thanks

**Comment by SergeShkurko** [comment]
See See https://github.com/rbcprolabs/packages.flutter/issues/6#issuecomment-961061302

**Comment by rakib205** [comment]
Still not working!
