### ISSUE TITLE
Shrink wrap option

### ISSUE THREAD

**Issue by Eufranio** [rbcprolabs/packages.flutter#200]
**Is your feature request related to a problem? Please describe.**
The PDFView widget takes the full width/height. When using the widget on a page, it created top/bottom borders.

**Describe the solution you'd like**
I'd like to have something like a `shrinkWrap` option in the PDFViewer, so the max. width/height it would have would be the PDF's page size. I'd like to have the widget take the full page width, but at least only the pdf page's height.

**Describe alternatives you've considered**
I've tried limiting the widget height value by putting it inside a limited Container, but not all PDFs have the same height.

**Additional context**
![image](https://user-images.githubusercontent.com/17598280/125378954-09789980-e366-11eb-9efe-76c9e0f2df05.png)
I'd like the widget to take only the page's space, shown by the white square. The red rectangles are created by the remaining space that the plugin fills with the background color.

**Comment by SergeShkurko** [comment]
See https://github.com/rbcprolabs/packages.flutter/issues/6#issuecomment-961061302
