### ISSUE TITLE
ePub reader crashes

### ISSUE THREAD

**Issue by moobydrey** [rbcprolabs/packages.flutter#21]
After installing your package and following the example, the app crashes with the error below

**RangeError (index): Invalid value: Valid value range is empty: 0**

**Comment by SergeShkurko** [comment]
@moobydrey can you clone repository and run example? https://github.com/rbcprolabs/packages.flutter/tree/master/packages/epub_view/example

**Comment by SergeShkurko** [comment]
native_pdf_render 1.6.2 published
native_pdf_view 1.2.1 published

**Comment by SergeShkurko** [comment]
or try use another epub file in you project
for example: https://github.com/rbcprolabs/packages.flutter/blob/master/packages/native_pdf_view/example/assets/sample.pdf

**Comment by moobydrey** [comment]
Okay thanks, i figured it out
