### ISSUE TITLE
Conflivt with other packages

### ISSUE THREAD

**Issue by Devlonoah** [rbcprolabs/packages.flutter#215]
On running flutter pub get  .
I keep getting conflict messages like

_So, because dobook depends on both encrypt ^5.0.0 and epub ^2.1.0, version solving failed.
pub get failed (1; So, because dobook depends on both encrypt ^5.0.0 and epub ^2.1.0, version solving failed.)
exit code 1_

**Comment by SergeShkurko** [comment]
Try use last package version: 2.3.0
