### ISSUE TITLE
epub_view Using webview as renderer

### ISSUE THREAD

**Issue by winterdl** [rbcprolabs/packages.flutter#216]
**Is your feature request related to a problem? Please describe.**
Using webview for renderer, as FolioReader or Readium, epubjs, all of them use webview as epub renderer. With webview we could render all kind of html tag as we want, pagination as using css column..

**Comment by SergeShkurko** [comment]
Yes, this is the way possible. But it meets our requirements. No plugin supports PC platforms, they are usually limited to phones
