### ISSUE TITLE
APP_NAME depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed

### ISSUE THREAD

**Issue by bipindubey-technoark** [rbcprolabs/packages.flutter#219]
I am getting this issue while running the flutter pub get.
I am not able to build an android apk.

`Because native_pdf_view 4.1.0 depends on photo_view ^0.11.1 and no versions of native_pdf_view match >4.1.0 <5.0.0, native_pdf_view ^4.1.0 requires photo_view ^0.11.1.
So, because flutter_funds_app depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed.
pub get failed (1; So, because flutter_funds_app depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed.)`

Thanks

**Comment by swarup13** [comment]
https://github.com/rbcprolabs/packages.flutter/issues/217

**Comment by bipindubey-technoark** [comment]
Thanks @swarup13 It fixed the issue
instead of putting photo view in dependency put it under dependency_overrides
```
dependency_overrides:
    photo_view: ^0.12.0
```
