### ISSUE TITLE
Cannot build apk release (compileSdkVersion 29)

### ISSUE THREAD

**Issue by yairsafe** [rbcprolabs/packages.flutter#22]
I can't build apk release (my compileSdkVersion is 29)
I get this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':native_pdf_renderer:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  
flutter\build\native_pdf_renderer\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
 flutter\build\native_pdf_renderer\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found. 
  error: failed linking references.

To resolve this error i increase **compileSdkVersion** in **build.gradle** of module **native_pdf_renderer**from **27** to **28**

I found this solution here

https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/207#issuecomment-424038966

So you need to increase compileSdkVersion to **28** in source code.
Thanks

**Comment by SergeShkurko** [comment]
native_pdf_render 1.6.2 published
native_pdf_view 1.2.1 published
