### ISSUE TITLE
[Improvement] Opening a pdf from  an url

### ISSUE THREAD

**Issue by lore-co** [rbcprolabs/packages.flutter#223]
**Is your feature request related to a problem? Please describe.**

As title says, it would be amazing to make possible rendering a pdf from an url.

**Describe the solution you'd like**
As above.

**Describe alternatives you've considered**
Unluckily other packages are quite lacking, and pdf_view is no longer mantained, along with cached_pdf_view.

**Additional context**

**Comment by SergeShkurko** [comment]
See https://github.com/rbcprolabs/packages.flutter/issues/6#issuecomment-961061302
