### ISSUE TITLE
[epub_view] Zoom IN/ Zoom Out Features

### ISSUE THREAD

**Issue by basnetjiten** [rbcprolabs/packages.flutter#226]
Hi, Can you please come up with zoom features for EpubViewer, 
Also during Zoom Out and Zoom In, can we track and set ePub-cfi

**Comment by SergeShkurko** [comment]
[epub_view] is fully flutter controlled package used for render flutter widgets. Epub content is html. And app show it use [flutter_html].
For text scale you can usage and other UI changes you can usage some params:
![image](https://user-images.githubusercontent.com/18213789/140332064-9b6f8ce2-affb-44d9-862b-6dccb5a87476.png)
