### ISSUE TITLE
Can not show digital signature in pdf file

### ISSUE THREAD

**Issue by trankienbk** [rbcprolabs/packages.flutter#229]
I can't show digital signature in pdf file.
Please see below comment

**Comment by SergeShkurko** [comment]
[Android naive api PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) used by this plugin don't support pdf annotations

**Comment by trankienbk** [comment]
> [Android naive api PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) used by this plugin don't support pdf annotations

How can I display digital signature? Do you have other plugin, which support display? Please reply me in facebook (https://www.facebook.com/trankienbk). Thank you so much

**Comment by LeszekLEO** [comment]
It looks, that [pdfRenderer ](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) has been expanded for Androind in API level 35. There is a new funciton 'render' for [pdfRenderer.Page](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.Page#render(android.graphics.Bitmap,%20android.graphics.Rect,%20android.graphics.Matrix,%20android.graphics.pdf.RenderParams)), in which new params (RenderParams) can be set: FLAG_RENDER_TEXT_ANNOTATIONS, FLAG_RENDER_HIGHLIGHT_ANNOTATIONS.

I also saw a few other open issues with questions for it:
https://github.com/ScerIO/packages.flutter/issues/442
https://github.com/ScerIO/packages.flutter/issues/485
https://github.com/ScerIO/packages.flutter/issues/497

Is it possible to solve this problem in the "pdfx" package for new Android versions?
