### ISSUE TITLE
[auto_animated] Export LiveOptions in library

### ISSUE THREAD

**Issue by kuhnroyal** [rbcprolabs/packages.flutter#23]
**Describe the bug**
`LiveOptions` has to be imported from `package:auto_animated/src/helpers/options.dart.

**Expected behavior**
Importing `package:auto_animated/auto_animated.dart` should make `LiveOptions` available.

**Comment by SergeShkurko** [comment]
Thanks, fix published in auto_animated [v2.0.1](https://pub.dev/packages/auto_animated/versions/2.0.1)
