### ISSUE TITLE
The Pdf doesn't scroll (Windows and Mac)

### ISSUE THREAD

**Issue by albert0m** [rbcprolabs/packages.flutter#260]
As in the title, the pdf doesn't scroll in any direction, both mac and windows (it works for instance in iOS).
If I change the page with the pageController the pages change and you can see the scroll animation (so there is something to scroll). If you try to drag the page, it doesn't move.

I'm not sure if this is the expected behaviour, I read the same problem from someone else in the comments of another ticket.

**Comment by albert0m** [comment]
the scroll is disabled by default on flutter desktop, sorry about that

**Comment by gwydi** [comment]
Are there plans to add this feature for Windows at some point?
