### ISSUE TITLE
Rendering Page crashes on iOS

### ISSUE THREAD

**Issue by Bendix20** [rbcprolabs/packages.flutter#29]
**Describe the bug**
When I try to render a PDF page the App crashes on an iOS device. There is no Exception, only the message :
"Lost connection to device.
Bad state: No element
Bad state: No element
Exited (sigterm)". 

On Android this is working fine.

**To Reproduce**
The App is crashing in line 6
```
void main() async {
  try {
  WidgetsFlutterBinding.ensureInitialized();
    final document = await PDFDocument.openAsset('assets/hello.pdf');
    final page = await document.getPage(1);
    final pageImage = await page.render(width: page.width, height: page.height);
    await page.close();
    runApp(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: Image(
              image: MemoryImage(pageImage.bytes),
            ),
          ),
        ),
        color: Colors.white,
      )
    );
  } on Exception catch (error) {
    print(error);
  }
}
```

**Comment by SergeShkurko** [comment]
@Bendix20 try re run example

**Comment by SergeShkurko** [comment]
and try it: https://github.com/flutter/flutter/issues/22299#issuecomment-587016400

**Comment by kcruzat** [comment]
Got the same issue to on iOS. It's because backgroundColor is a mandatory parameter. It doesn't have a default value too. I guess it works on Android fine without it.

**Comment by Bendix20** [comment]
@kcruzat Thats it. Thank you!
