### ISSUE TITLE
[native_pdf_view] can't load files with japanese filenames.

### ISSUE THREAD

**Issue by Nomy1** [rbcprolabs/packages.flutter#35]
**Describe the bug**
Cannot load files with japanese filenames.

**To Reproduce**
1. Clone example project.
2. Rename sample.pdf to 日本語.pdf
3. Rename pubspec.yaml asset file reference from sample.pdf to 日本語.pdf
3. Change sample.pdf String in main.dart to 日本語.pdf
4. packages get
5. run main.dart

**Expected behavior**
open file.

**Additional context**
project works fine when the file is sample.pdf, and even if i change the filename to 123.pdf. but fails when it uses japanese.

**Comment by SergeShkurko** [comment]
I would not recommend using any locale other than English. You can temporarily rename the file, or [load file into memory](https://api.dart.dev/stable/2.7.1/dart-io/File/readAsBytes.html) and open with `PDFDocument.openData(Uint8List)`
