### ISSUE TITLE
Using AutoAnimatedSliverList with Dismissible child causes list to redraw when OnDismissed() gets called

### ISSUE THREAD

**Issue by emvaized** [rbcprolabs/packages.flutter#36]
**Describe the bug**
My Dismissible widget contains 
```
setState((){
_items.removeAt(index);
})
``` 
callback in onDismissed() method. 

Previously I used SliverList, and it handled it perfectly -- item was removed without any errors. Now, with AutoAnimatedSliverList(), my onDismissed() method causes whole list to redraw and scroll to top.

**To Reproduce**
1. Use Dismissible() widget as a child for AutoAnimatedSliverList();
2. Try to swipe on element;
3. See AutoAnimatedSliverList redrawed.

**Expected behavior**
I expected it to behave as SliverList, handling Dismissible behavior under the hood.

At least it must be explained in documentation on how to solve similar issue, probably using some GlobalKey<AutoAnimatedListState>.

**Comment by SergeShkurko** [comment]
@emvaized which version of the package do you use? at  v2.0 AutoAnimatedSliverList renamed to LiveSliverList  and the library as a whole has been rewritten. Could you double-check with the new version?

**Comment by emvaized** [comment]
> @emvaized which version of the package do you use? at [v2.0](https://pub.dev/packages/auto_animated/versions/2.0.2) AutoAnimatedSliverList renamed to LiveSliverList and the library as a whole has been rewritten. Could you double-check with the new version?

Thanks a lot, everything works now! 
Just needed to update Dart to last version, and auto_animated updated as well.

I'm closing this issue now. Thanks again.
