### ISSUE TITLE
Add possibility to define infinite zoom parameter

### ISSUE THREAD

**Issue by enricobenedos** [rbcprolabs/packages.flutter#45]
**Is your feature request related to a problem? Please describe.**
Actually I started using this package due to the fact that it uses the native iOS and Android API.
I need to permit user to zoom infinitely on my `PDFView`, but now zoom is not simply settable. In some PDF page the actual zoom is not enough. 

**Describe the solution you'd like**
It will be beautiful to add a parameter on `PDFView` widget in order to set the maximum PDF zoom/zoomRatio in a simply way. Something like:
```dart
return PDFView(
                  document: snapshot.data,
                  infiniteZoom: true/false,
                  // or maxZoomRatio: 4.0,
                );
```

Can it be possible?

Thank you

**Comment by SergeShkurko** [comment]
@enricobenedos you can usage [custom-page-builder](https://pub.dev/packages/native_pdf_view#custom-page-builder)
