### ISSUE TITLE
page take a noticeable time to load

### ISSUE THREAD

**Issue by Fethi1** [rbcprolabs/packages.flutter#47]
when the pdf file is loaded pages takes time to load even in release which is pretty annoying for book readers and it is even worse for pages that contain images, is there any to make it faster?

**Comment by emreesen27** [comment]
Do you use FutureBuilder ?

**Comment by Fethi1** [comment]
yes, i copied the example

**Comment by Fethi1** [comment]
the pdf file i'm trying to display is from device's storage not assets, can that be the issue?

**Comment by emreesen27** [comment]
I don't think there is a problem with this. I use a similar method and I have no performance issues. I must mention that I am working on large pdf files.

`PDFDocument _document;`

`  Future<PDFDocument> _getDocument() async { `  
   ` return _document = await PDFDocument.openFile(your path+ "/file.pdf"); `
` }`


> 

`FutureBuilder<PDFDocument>(`
`   future: _getDocument(),`
`   builder: (_, snapshot) { `
`   if(snapshot.hasdata) { `
`    return PDFView()... }`
`}`
`)`

**Comment by SergeShkurko** [comment]
@Fethi1 where you run project? On real device in debug mod or emulator in debug mode?

**Comment by Fethi1** [comment]
i run it on a real device, i have tried it on both debug and release and in different phones and the same thing happen, especially for pages that has images, it takes some time to load.
the app i'm developing is supposed to fetch pdf files on device and display each file on a new Route

**Comment by SergeShkurko** [comment]
You can play with render option ([render docs](https://pub.dev/documentation/native_pdf_renderer/latest/native_pdf_renderer/PDFPage/render.html))

```dart
PDFView(
  controller: pageController,
  renderer: (PDFPage page) => page.render(
    width: page.width * 2, // for example set to 1.25-1.5
    height: page.height * 2,
    format: PDFPageFormat.JPEG,
    backgroundColor: '#FFFFFF',
  ),
);
```

pages are converted to an image and part of the time is spent on transfer from dart side to platform and back

**Comment by atheist1** [comment]
@SergeShkurko it seems converted page to an image spent lots of time  when i use `animateToPage` or other animation api .There is a black area on the bottom.what should i do to solve the problem?

**Comment by deakjahn** [comment]
@SergeShkurko please change the example as I described in https://github.com/rbcprolabs/packages.flutter/issues/46#issuecomment-615361536

You shouldn't load the PDF this way into a `FutureBuilder`. This results in **many** repeated loads of the file and is explicitely recommended against in the Flutter documentation.

**Comment by SergeShkurko** [comment]
@atheist1 usage jumpTo or minimize delay

**Comment by SergeShkurko** [comment]
@deakjahn i change api un 3.0.0, it is no longer required

**Comment by SergeShkurko** [comment]
option renderer was not working until 3.0.0, now fixed
