### ISSUE TITLE
Repeatedly loaded PDF file doesn't replace previous pages

### ISSUE THREAD

**Issue by deakjahn** [rbcprolabs/packages.flutter#51]
If I read the new PDF file instead of the existing one (eg. using a `StreamBuilder`), already rendered and probably cached pages will not be replaced with the pages from the new file. Only pages not yet visited in the previous PDF will be rendered correctly.

**Expected behavior**
Loading a new PDF should invalidate previously cached pages.

**Comment by SergeShkurko** [comment]
did not encounter such problems
show your code

**Comment by deakjahn** [comment]
StreamController<PDFDocument> document = StreamController<PDFDocument>();
    PDFDocument current;
    PageController controller;

    void setDocument(String path) {
      readAsset('assets/$path').then((data) {
        PDFDocument.openData(data).then((pdf) {
          current?.close();
          document.add(pdf);
        });
      });
    }

    @override
    Widget build(BuildContext context) => StreamBuilder<PDFDocument>(
          stream: document.stream,
          builder: (context, snapshot) {
            if (snapshot.hasError)
              return Center(child: Text('PDF error'));
            else if (snapshot.hasData) {
              current = snapshot.data;
              return PDFView.builder(
                controller: controller,
                document: snapshot.data,
                scrollDirection: Axis.horizontal,
              );
            } else
              return Center(child: CircularProgressIndicator());
          },
        );

**Comment by SergeShkurko** [comment]
try add Unique key

```dart
return PDFView.builder(
  key: UniqueKey(), // <- here
  controller: controller,
  document: snapshot.data,
  scrollDirection: Axis.horizontal,
)
```

**Comment by deakjahn** [comment]
Yes, the key seems to help.
