### ISSUE TITLE
[native_pdf_view]some pdf show error

### ISSUE THREAD

**Issue by atheist1** [rbcprolabs/packages.flutter#52]
**Describe the bug**
I want to play .xls or .xlxs .doc format file on my device.but i cant find any plugin on flutter to show it.so i just transformed the file to the pdf format, the file transformed from .doc format show nothing error but the file transformed from .xls format shows nothing but white screen(if the font color is black and the background color is white).If I changed the font color to  red i can see the word render an red line on the screen.  
The file shows no error on my computer.

**Screenshots**
![11587438545_ pic](https://user-images.githubusercontent.com/27856388/79821151-99789f00-83c0-11ea-9565-a84ff3ae78ad.jpg)

**Smartphone (please complete the following information):**
 - Device: RK3128 BOX
 - OS: android 7.1
 - Version [2.2.1]

**Additional context**
I can provide the original file if necessary.  
Waiting for u reply.Thx.

**Comment by SergeShkurko** [comment]
try using a different format converter
