### ISSUE TITLE
page not loaded when onDocumentLoaded and onPageChanged are not set

### ISSUE THREAD

**Issue by boskokg** [rbcprolabs/packages.flutter#57]
I don't have a need to be notified of onDocumentLoaded and onPageChanged events. Since the arguments are not marked as mandatory I didn't set onDocumentLoaded and onPageChanged.

As I saw your code expects that this callbacks are set and loading document crashes...

You should probably mark fields as mandatory or do a null check in the code before calling methods.

**Comment by SergeShkurko** [comment]
fixed in 3.0.1
