### ISSUE TITLE
[native_pdf_view] Vertical smooth viewer

### ISSUE THREAD

**Issue by boskokg** [rbcprolabs/packages.flutter#59]
I am trying to switch from pdf_viewer_plugin to your package but I am not able to implement the same user experience as I have in the existing plugin.

What I need is vertical viewer with smooth scrolling. I need the page to load in full available width size (both in portrait and horizontal orientation). I need pinch/zoom possibility. The zoom should not reset when the new page is detected.

Basically, it should look like all pdf pages are merged vertically as the one big page and initially shown in the full available width space, with zoom and pinch possibility.

Can you please help me archive that with your plugin.

**Comment by SergeShkurko** [comment]
You can usage for vertical scrolling
```
 scrollDirection: Axis.vertical,
```
also you can play with properties in builder
![image](https://user-images.githubusercontent.com/18213789/80695875-38974800-8adf-11ea-9920-c73461273c1a.png)

**Comment by boskokg** [comment]
I tried but with no luck.
Can you please tell me how should I configure?

**Comment by saptha** [comment]
When I use BoxFit.fitWidth I cannot see any text while in landscape mode. I'm using the latest version (3.2.0). Can you kindly suggest?

**Comment by SergeShkurko** [comment]
I working on it in #6
