### ISSUE TITLE
Changelog is wrong

### ISSUE THREAD

**Issue by lazylazyllama** [rbcprolabs/packages.flutter#60]
Something went wrong in the changelog regarding 2.0.0

![image](https://user-images.githubusercontent.com/10547444/80757425-6f4b7d80-8b34-11ea-965d-25cbdc8602e5.png)

shouldn't it be PDF on the left hand side? And not Pdf?

**Comment by SergeShkurko** [comment]
thanks, fixed in 2.0.1
