### ISSUE TITLE
Desktop and web support for Native PDF view

### ISSUE THREAD

**Issue by Sadmansamee** [rbcprolabs/packages.flutter#63]
The current implementation seems to be only for Android and iOS, is there any way to use this plugin for desktop and web?

**Comment by SergeShkurko** [comment]
currently working on support web

**Comment by SergeShkurko** [comment]
Web support added in [3.3.0](https://pub.dev/packages/native_pdf_view/versions/3.3.0)

**Comment by Sadmansamee** [comment]
great!

**Comment by SergeShkurko** [comment]
MacOs support added in [3.4.0](https://pub.dev/packages/native_pdf_view/versions/3.4.0)
