### ISSUE TITLE
How to convert PDFPageImage to image inorder to view PDF file as Image ?

### ISSUE THREAD

**Issue by jazzbpn** [rbcprolabs/packages.flutter#66]
imageFromPdfFile2(File pdfFile) async {
        List<im.Image> imageList = List();
        int height = 0, width = 0;

        final document = await pdf_ren.PDFDocument.openFile(pdfFile.path);
        im.Image imImage;
        for (int i = 1; i <= document.pagesCount; i++) {
          final page = await document.getPage(i);
          final pdfPageImage =
              await page.render(width: page.width, height: page.height);
          imImage = im.decodeImage(pdfPageImage.bytes); // First issue in this line
          height += imImage.height;
          width += imImage.width;
          imageList.add(imImage);
          await page.close();
        }

        im.Image mergedImage = im.Image(width, height);
        // Merge generated image vertically as vertical-orientated-multi-pdf
        for (var item in imageList) {
          im.copyInto(mergedImage, item, blend: true);
        }

        savePdfAndImageDB(pdfFile, imImage.getBytes());
      }

**Comment by SergeShkurko** [comment]
Future<PdfPageImage> _renderPage(PdfDocument document, int pageNumber) async {
    final page = await document.getPage(pageNumber);
    final pageImage = await page.render(
      width: page.width * 2,
      height: page.height * 2,
      format: PdfPageFormat.PNG,
    );
    await page.close();
    return pageImage;
  }

**Comment by SergeShkurko** [comment]
for you code
```dart
  imageFromPdfFile2(File pdfFile) async {
    List<im.Image> imageList = List();
    int height = 0, width = 0;

    final document = await pdf_ren.PDFDocument.openFile(pdfFile.path);
    im.Image imImage;
    for (int i = 1; i <= document.pagesCount; i++) {
      final page = await document.getPage(i);
      final pdfPageImage =
          await page.render(width: page.width, height: page.height);
      imImage = im.decodeImage(pdfPageImage.bytes); // First issue in this line
      height += imImage.height;
      // the width should correspond to the maximum 
      // width of the image: it should not exceed it
      if (imImage.width > width ) {
          width =  imImage.width;
      }
      imageList.add(imImage);
      await page.close();
    }

    im.Image mergedImage = im.Image(width, height);
    // Merge generated image vertically as vertical-orientated-multi-pdf
    for (var i = 0; i < imageList.length; i++) {
      final onePageImageOffset = height / document.pagesCount;
      // offset for actual page from by y axis
      final actualPageOffset = onePageImageOffset  * i;
      // need to copy image with offset 
      // I do not know where this function comes from or how it works. 
      im.copyInto(mergedImage, imageList[i], blend: true);
    }

    savePdfAndImageDB(pdfFile, imImage.getBytes());
  }
```

or you can usage native_pdf_view package

**Comment by jazzbpn** [comment]
Still facing issue in the line:

`      im.copyInto(
           mergedImage, 
           imageList[i], 
           blend: true,
           srcY: actualPageOffset, // or dstY
      );`

<img width="1110" alt="Screen Shot 2020-05-17 at 16 55 55" src="https://user-images.githubusercontent.com/11361035/82142876-614d6a80-985f-11ea-98d3-2ce595f1197d.png">

**Comment by SergeShkurko** [comment]
try modify

```
    im.Image mergedImage = im.Image(width, height);
    // Merge generated image vertically as vertical-orientated-multi-pdf
    for (var i = 0; i < imageList.length; i++) {
      // one page height
      final onePageImageOffset = height / document.pagesCount;

     final isLast = i + 1 == imageList.length;

      // offset for actual page from by y axis
      final actualPageOffset = onePageImageOffset  * i;

      im.copyInto(
           mergedImage, 
           imageList[i], 
           blend: true,
           srcY: isLast ? actualPageOffset - 1 : actualPageOffset, // or dstY
      );
    }

```

**Comment by jazzbpn** [comment]
Still same issue. Full function:

     
    imageFromPdfFileFullImage(File pdfFile) async {
      List<im.Image> imageList = List();
      int height = 0, width = 0;

      final document = await render.PDFDocument.openFile(pdfFile.path);
      im.Image imImage;
      for (int i = 1; i <= document.pagesCount; i++) {
        final page = await document.getPage(i);
        final pdfPageImage =
            await page.render(width: page.width, height: page.height);
        imImage = im.decodeImage(pdfPageImage.bytes); // First issue in this line
        height += imImage.height;
        // the width should correspond to the maximum
        // width of the image: it should not exceed it
        if (imImage.width > width) {
          width = imImage.width;
        }
        imageList.add(imImage);
        await page.close();
      }

      im.Image mergedImage = im.Image(width, height);

      // Merge generated image vertically as vertical-orientated-multi-pdf
      for (var i = 0; i < imageList.length; i++) {
        // one page height
        final onePageImageOffset = height / document.pagesCount;

        final isLast = i + 1 == imageList.length;

        // offset for actual page from by y axis
        final actualPageOffset = onePageImageOffset * i;

        im.copyInto(
          mergedImage,
          imageList[i],
          blend: true,
          srcY: isLast
              ? actualPageOffset.round() - 1
              : actualPageOffset.round(), // or dstY
        );
      }
      savePdfAndImageToFirebase(pdfFile, imImage.getBytes());
    } 

<img width="1098" alt="Screen Shot 2020-05-19 at 09 30 57" src="https://user-images.githubusercontent.com/11361035/82282484-a8e50b00-99b3-11ea-81ee-4a4f5ace1728.png">

**Comment by SergeShkurko** [comment]
exactly working method
```dart
import 'dart:async';

import 'package:image/image.dart' as im;
import 'package:flutter/material.dart';
import 'package:native_pdf_renderer/native_pdf_renderer.dart';

Future<List<int>> imageFromPdfFileFullImage(Future<PdfDocument> pdfFile) async {
  final List<im.Image> imageList = List();
  int height = 0, width = 0;

  final document = await pdfFile;
  im.Image imImage;
  for (int i = 1; i <= document.pagesCount; i++) {
    final page = await document.getPage(i);
    final pdfPageImage = await page.render(
        width: page.width, height: page.height, format: PdfPageFormat.JPEG);
    imImage = im.decodeJpg(pdfPageImage.bytes); // First issue in this line
    height += imImage.height;
    // the width should correspond to the maximum
    // width of the image: it should not exceed it
    if (imImage.width > width) {
      width = imImage.width;
    }
    imageList.add(imImage);
    await page.close();
  }

  final im.Image mergedImage = im.Image(width, height);

  // Merge generated image vertically as vertical-orientated-multi-pdf
  for (var i = 0; i < imageList.length; i++) {
    // one page height
    final onePageImageOffset = height / document.pagesCount;

    // offset for actual page from by y axis
    final actualPageOffset = i == 0 ? 0 : onePageImageOffset * i - 1;

    im.copyInto(
      mergedImage,
      imageList[i],
      blend: true,
      srcW: width,
      srcH: onePageImageOffset.round(),
      dstY: actualPageOffset.round(),
    );
  }
  return im.encodePng(mergedImage);
}

void main() => runApp(ExampleApp());

class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PDF View example',
      color: Colors.white,
      home: Scaffold(
          body: FutureBuilder<List<int>>(
              future: imageFromPdfFileFullImage(
                  PdfDocument.openAsset('assets/sample.pdf')),
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return Center(child: CircularProgressIndicator());
                }
                return Image(
                  image: MemoryImage(snapshot.data),
                );
              })),
    );
  }
}

```

**Comment by AverageChau** [comment]
Is there a way to add padding/offset or transparent space in between images?
