### ISSUE TITLE
Improved Scrolling on Web for native_pdf_view

### ISSUE THREAD

**Issue by flowhorn** [rbcprolabs/packages.flutter#69]
Currently scrolling on web is possible using gestures like on Mobile. But it would be great to support scrolling using the mouse and a scrollbar.

**Comment by SergeShkurko** [comment]
what package are you talking about?

**Comment by flowhorn** [comment]
> what package are you talking about?

native_pdf_view. Sorry, I forgot, that there are multiple packages in this repo.

**Comment by SergeShkurko** [comment]
Added in [3.5.0](https://pub.dev/packages/native_pdf_view#350)
use `pageSnapping: false` in `PdfView`
