### ISSUE TITLE
New dependencies error.

### ISSUE THREAD

**Issue by akinfurkann** [rbcprolabs/packages.flutter#72]
epub_view| 
Because epub_view >=0.2.0 depends on epub ^2.1.0 and epub_view <0.2.0 depends on epub ^2.0.0, every version of epub_view requires epub ^2.0.0.

So, because epub depends on epub_view any and epub is 1.0.0+1, version solving failed.
pub get failed (1; So, because epub depends on epub_view any and epub is 1.0.0+1, version solving failed.)

**Comment by SergeShkurko** [comment]
you have a package dependency somewhere epub

try add in pubspec
```yaml
dependency_overrides:
  epub: ^2.1.0
```
