### ISSUE TITLE
Getting "Don't import implementation files from another package"

### ISSUE THREAD

**Issue by sgehrman** [rbcprolabs/packages.flutter#73]
Just started seeing this, but for web targets, the generated_plugin_regstrant.dart file is now complaining about 
import 'package:native_pdf_renderer/src/web/native_pdf_renderer_plugin.dart';

This file is autogenrated, so not sure how to fix.  This might help. https://stackoverflow.com/questions/52925209/error-dont-import-implementation-files-from-another-package

I am not  trying to use this on web, I have your package included in a library that is shared with my web project.

**Comment by SergeShkurko** [comment]
you can exclude file from linter
https://medium.com/better-programming/dont-panic-when-flutter-generates-a-bad-file-for-you-e5e314c2b01

like a https://github.com/rbcprolabs/packages.flutter/blob/master/analysis_options.yaml#L4
