### ISSUE TITLE
[native_pdf_renderer] Possible incorrect iOS version constraint

### ISSUE THREAD

**Issue by Jon-Salmon** [rbcprolabs/packages.flutter#74]
In the readme, the minimum version for iOS is stated as 11.0+ (this was committed 9 months ago with no comment that I can find).

However, as far as I can tell PdfKit isn't used anywhere in the plug-in but instead CGPDFPage is used instead which was introduced in iOS 2.0.

Am I missing something or should the readme be updated?

**Comment by SergeShkurko** [comment]
You are probably right and I made a mistake when writing a readme. In the near future I will try to check

**Comment by Jon-Salmon** [comment]
Thanks for looking at this and thanks for building this fantastic package
