### ISSUE TITLE
[Web] Viewport width/height

### ISSUE THREAD

**Issue by chriswm3** [rbcprolabs/packages.flutter#76]
Hi,

The following getters can throw an exeption, because _viewport.width and height could be double:

document/page.dart

```
Line 24  int get width => _viewport.width;
Line 24  int get height => _viewport.height;
```
should be:

```
  int get width => _viewport.width.toInt();
  int get height => _viewport.height.toInt()
```
like Line 51:

```
 canvas
      ..height = viewport.height.toInt()
      ..width = viewport.width.toInt();
```

**Comment by SergeShkurko** [comment]
@chriswm3 `_viewport` sets only in constructor: https://github.com/rbcprolabs/packages.flutter/blob/master/packages/native_pdf_renderer/lib/src/web/document/page.dart#L16

variable `viewport` initialize in render method

**Comment by chriswm3** [comment]
@SergeShkurko 
But when the infoMap is created the height and width getter will be called,

Then i get a PlatformException:
Error: Expected a value of type 'int', but got one of type 'double'

**Comment by SergeShkurko** [comment]
thanks
