### ISSUE TITLE
How to use load document in native_pdf_view?

### ISSUE THREAD

**Issue by ASSASSIN-363** [rbcprolabs/packages.flutter#78]
How to load another document in native_pdf_view. can you provide an example?

**Comment by SergeShkurko** [comment]
> How to load another document in native_pdf_view. can you provide an example?

PdfController has member "loadDocument()"

**Comment by ASSASSIN-363** [comment]
I tried
_pdfController.loadDocument(PdfDocument.openAsset('assets/dummy.pdf'));
but nothing happens
I am using it in flutter web.

**Comment by ASSASSIN-363** [comment]
import 'package:flutter/material.dart';
import 'package:native_pdf_view/native_pdf_view.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int _actualPageNumber = 1, _allPagesCount = 0;
  PdfController _pdfController;

  @override
  void initState() {
    _pdfController = PdfController(
      document: PdfDocument.openAsset('assets/sample.pdf'),
    );
    super.initState();
  }

  @override
  void dispose() {
    _pdfController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        theme: ThemeData(primaryColor: Colors.white),
        home: Scaffold(
          appBar: AppBar(
            title: Text('PdfView example'),
            actions: <Widget>[
              RaisedButton(
                color: Colors.amber,
                onPressed: () {
                  _pdfController
                      .loadDocument(PdfDocument.openAsset('assets/dummy.pdf'));
                },
              ),
              IconButton(
                icon: Icon(Icons.navigate_before),
                onPressed: () {
                  _pdfController.previousPage(
                    curve: Curves.ease,
                    duration: Duration(milliseconds: 100),
                  );
                },
              ),
              Container(
                alignment: Alignment.center,
                child: Text(
                  '$_actualPageNumber/$_allPagesCount',
                  style: TextStyle(fontSize: 22),
                ),
              ),
              IconButton(
                icon: Icon(Icons.navigate_next),
                onPressed: () {
                  _pdfController.nextPage(
                    curve: Curves.ease,
                    duration: Duration(milliseconds: 100),
                  );
                },
              ),
            ],
          ),
          body: PdfView(
            loaderSwitchDuration: Duration(milliseconds: 100),
            pageSnapping: false,
            scrollDirection: Axis.vertical,
            documentLoader: Center(child: CircularProgressIndicator()),
            pageLoader: Center(child: CircularProgressIndicator()),
            controller: _pdfController,
            onDocumentLoaded: (document) {
              setState(() {
                _allPagesCount = document.pagesCount;
              });
            },
            onPageChanged: (page) {
              setState(() {
                _actualPageNumber = page;
              });
            },
          ),
        ),
      );
}

**Comment by SergeShkurko** [comment]
1. try stop build
2. run flutter clear
3. then start project

**Comment by ASSASSIN-363** [comment]
> 1. try stop build
> 2. run flutter clear
> 3. then start project

I used flutter clean and ran the project again but still, nothing is happening can u check the above code(appbar actions raised button).

should I call it in setstate ?

**Comment by ASSASSIN-363** [comment]
can you pls provide an example on how to use "loadDocument()"
I really need this plugin and "loadDocument()" function for a projects.
:)

**Comment by ASSASSIN-363** [comment]
can u give a small example how to use the "loadDocument()" member ?

**Comment by SergeShkurko** [comment]
fixed in 3.6.2
