### ISSUE TITLE
getFromURL

### ISSUE THREAD

**Issue by DennisSchm** [rbcprolabs/packages.flutter#79]
I really would like to have a simple solution of getting the PDF to render via URL. Would make things much easier and would make sense since the plugin is working in web and therefore providing an option to read PDFs while not having to leave the application.

**Comment by SergeShkurko** [comment]
I see no reason to connect the package to work with the HTTP protocol, this is solved by one function
for example:
```dart
import 'package:path_provider/path_provider.dart';
import 'package:http/http.dart' as http;

 PdfController _pdfController;

  Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();

    return directory.path;
  }

  Future<File> get _localFile async {
    final path = await _localPath;
    return File('$path/exemplo.pdf');
  }

  Future<File> writeCounter(Uint8List stream) async {
    final file = await _localFile;

    // Write the file
    return file.writeAsBytes(stream);
  }

  Future<Uint8List> fetchPost() async {
    final response = await http.get(
        'https://expoforest.com.br/wp-content/uploads/2017/05/exemplo.pdf');
    final responseBytes = response.bodyBytes;

    return responseBytes;
  }

   String loadPdf() async {
    writeCounter(await fetchPost());
    return (await _localFile).path;
  }

  @override
  void initState() {
   loadPdf().then((path) {
    _pdfController = PdfController(
    document: PdfDocument. openFile(path),
   );
   });

  }

@override
 Widget build() {
 if (_pdfController == null) return SizedBox();
return PdfView(
  controller: _pdfController,
);
}
```

**Comment by fauzipadlaw** [comment]
@SergeShkurko I tried your snippet but it force closed my app and got this message:
```
E/AndroidRuntime(14237): FATAL EXCEPTION: Thread-4
E/AndroidRuntime(14237): Process: com.the_elxr.app, PID: 14237
E/AndroidRuntime(14237): java.io.IOException: cannot create document. Error: 3
E/AndroidRuntime(14237): 	at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
E/AndroidRuntime(14237): 	at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:165)
E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.openFileDocument(NativePDFRendererPlugin.kt:202)
E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.access$openFileDocument(NativePDFRendererPlugin.kt:30)
E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openDocumentFileHandler$1.run(NativePDFRendererPlugin.kt:70)
E/AndroidRuntime(14237): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by AkshayNG** [comment]
> @SergeShkurko I tried your snippet but it force closed my app and got this message:
> 
> ```
> E/AndroidRuntime(14237): FATAL EXCEPTION: Thread-4
> E/AndroidRuntime(14237): Process: com.the_elxr.app, PID: 14237
> E/AndroidRuntime(14237): java.io.IOException: cannot create document. Error: 3
> E/AndroidRuntime(14237): 	at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
> E/AndroidRuntime(14237): 	at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:165)
> E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.openFileDocument(NativePDFRendererPlugin.kt:202)
> E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.access$openFileDocument(NativePDFRendererPlugin.kt:30)
> E/AndroidRuntime(14237): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openDocumentFileHandler$1.run(NativePDFRendererPlugin.kt:70)
> E/AndroidRuntime(14237): 	at java.lang.Thread.run(Thread.java:761)
> ```

Sometimes, I'm also facing the same issue `java.io.IOException: cannot create document. Error: 3`
