### ISSUE TITLE
[native_pdf_view] PDF Zoom is a little buggy

### ISSUE THREAD

**Issue by nilsreichardt** [rbcprolabs/packages.flutter#83]
**Describe the bug**
Zooming between two pages is a little bit buggy. See in this video: https://youtu.be/GoQg5maYswE

**To Reproduce**
1. Open a multi page pdf
2. Scroll to the end of a pdf
3. Double click on a page

**Expected behavior**
Zoom in and out in the whole pdf view, like:
![ExpectedZooming](https://user-images.githubusercontent.com/24459435/83952045-4b1b4480-a836-11ea-81a3-20d0c7ce3667.gif)

**Smartphone (please complete the following information):**
 - Web

**Comment by rakib205** [comment]
Same here. My users are also reporting this issue.

**Comment by SergeShkurko** [comment]
I working on it in #6
