### ISSUE TITLE
[native_pdf_view] Hotkey zoom in a PDF View

### ISSUE THREAD

**Issue by nilsreichardt** [rbcprolabs/packages.flutter#84]
It would be nice, if you could scroll with Control + mouse scroll (if mouse position is in the pdf view), like in a normal PDF program.

Demo:
![ExpectedZooming](https://user-images.githubusercontent.com/24459435/83952045-4b1b4480-a836-11ea-81a3-20d0c7ce3667.gif)

**Comment by kanekv** [comment]
@nilsreichardt Hello Nils, kind of offtopic question: how did you enable those pdf controls on the web (download/print/zoom/etc)?

Thanks!

**Comment by SergeShkurko** [comment]
See https://github.com/rbcprolabs/packages.flutter/issues/6#issuecomment-961061302
