### ISSUE TITLE
It can display the pdf, but can't display the signature and seal in the pdf

### ISSUE THREAD

**Issue by albertbxl** [rbcprolabs/packages.flutter#85]
what should I do ?

**Comment by albertbxl** [comment]
[mainContract.1.pdf](https://github.com/rbcprolabs/packages.flutter/files/4745237/mainContract.1.pdf)

**Comment by albertbxl** [comment]
second question: 
how to use pdf.js in  both android and iOS, I know change code,  pdf.js can support display signature and seal in pdf, what should I do ? thx

**Comment by dhymark** [comment]
similar question, signature is dismiss.how to solve it ?
