### ISSUE TITLE
Add initialPage to PdfController loadDocument method

### ISSUE THREAD

**Issue by chriswm3** [rbcprolabs/packages.flutter#89]
Please add initialPage as optional parameter to the loadDocument function of the PdfController.

**Comment by SergeShkurko** [comment]
Now parameter required?

**Comment by chriswm3** [comment]
If i loaded a PDF at first time i would do:

```
 pdfController = pdfviewer.PdfController(
              document: _loadPDF(),
              initialPage: 5
          );
```
Now i will load another document , page 5:

`pdfController.loadDocument(_loadPDF(),initialPage: 5);``

**Comment by SergeShkurko** [comment]
you can use
```dart
pdfController.loadDocument(_loadPDF()).then((data) { pdfController.jump(5); });
```

**Comment by SergeShkurko** [comment]
Added in [v3.7.0](https://pub.dev/packages/native_pdf_view/versions/3.7.0)
