### ISSUE TITLE
[native_pdf_view] Windows support

### ISSUE THREAD

**Issue by YavuzDev** [rbcprolabs/packages.flutter#90]
Is it possible to add windows support?

**Comment by SergeShkurko** [comment]
perhaps.
but I do not know cpp :)

https://flatteredwithflutter.com/flutter-desktop-plugin/
https://docs.microsoft.com/ru-ru/archive/msdn-magazine/2013/december/windows-8-1-rendering-pdf-content-in-windows-store-apps

**Comment by Jon-Salmon** [comment]
I have created pull request #174 for this.

**Comment by SergeShkurko** [comment]
[native_pdf_renderer] v3.1.0 & [native_pdf_view] v4.1.0 with Windows support published
