### ISSUE TITLE
Crash When Switching Between PDF's

### ISSUE THREAD

**Issue by NoahJApps** [rbcprolabs/packages.flutter#93]
When switching between PDF's, I am getting the following error

![Screen Shot 2020-06-29 at 10 06 33 pm](https://user-images.githubusercontent.com/43624635/86003231-db733080-ba54-11ea-9e9f-555333cb74ea.png)

This is something I'm getting straight after adding the library, isn't an error in the way I am using the library as far as I can tell. My code is below incase. 

`import 'package:cc_kounta/Classes/library_object.dart';
import 'package:cc_kounta/main.dart';
import 'package:flutter/material.dart';
import 'package:native_pdf_view/native_pdf_view.dart';

class LibraryScreen extends StatefulWidget {
  @override
  _LibraryScreenState createState() => _LibraryScreenState();
}

class _LibraryScreenState extends State<LibraryScreen> {
  final List<LibraryObject> pdfList = [
    LibraryObject(
        documentName: 'Burger Prep Guide',
        documentPath: 'lib/assets/BurgerPrepGuide.pdf',
        scrollVertical: false),
    LibraryObject(
        documentName: 'Delivery Guide',
        documentPath: 'lib/assets/DeliveryGuide.pdf',
        scrollVertical: false),
    LibraryObject(
        documentName: 'Milkshake Prep Guide',
        documentPath: 'lib/assets/MilkshakePrepGuide.pdf',
        scrollVertical: true),
  ];

  PdfController pdfController;
  bool shouldScrollVertical = false;

  @override
  void initState() {
    pdfController = PdfController(
      document: PdfDocument.openAsset('lib/assets/DeliveryGuide.pdf'),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Library',
          style: TextStyle(fontSize: 30.0),
        ),
      ),
      body: Row(
        children: <Widget>[
          Expanded(
            flex: 2,
            child: Container(
              padding: EdgeInsets.all(15),
              child: ListView.builder(
                itemCount: pdfList.length,
                itemBuilder: (ctx, index) {
                  return GestureDetector(
                    onTap: () {
                      setState(
                        () {
                          pdfController.loadDocument(
                            PdfDocument.openAsset(pdfList[index].documentPath),
                          );

                          shouldScrollVertical = pdfList[index].scrollVertical;
                        },
                      );
                    },
                    child: Container(
                      child: Column(
                        children: <Widget>[
                          Row(
                            children: <Widget>[
                              Icon(
                                Icons.insert_drive_file,
                                size: 40.0,
                                color: MyApp.customRed,
                              ),
                              SizedBox(
                                width: 5,
                              ),
                              Text(
                                pdfList[index].documentName,
                                style: TextStyle(fontSize: 20.0),
                              ),
                            ],
                          ),
                          SizedBox(
                            height: 5,
                          ),
                          Divider(
                            height: 1,
                            thickness: 1,
                          ),
                          SizedBox(
                            height: 20,
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
          ),
          Expanded(
            flex: 5,
            child: Container(
              color: Colors.grey[400],
              child: PdfView(
                scrollDirection:
                    shouldScrollVertical ? Axis.vertical : Axis.horizontal,
                pageLoader: Center(child: CircularProgressIndicator()),
                controller: pdfController,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by gilthonweapps** [comment]
Hi.
I have same issue.

**Comment by SergeShkurko** [comment]
Added in [v3.7.0](https://pub.dev/packages/native_pdf_view/versions/3.7.0)
